### ISSUE TITLE
Deploying to Heroku doesn't work

### ISSUE THREAD

**Issue by TobiasWehrum** [gilamran/fullstack-typescript#19]
When deploying to Heroku, the automatically run ```npm start``` produces the following error:

```
> fullstack-typescript@1.0.0 start /app
> node index.js

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'tslib'
Require stack:
- /app/dist/server-root/server/routes/pages-router.js
- /app/dist/server-root/server/main.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/app/dist/server-root/server/routes/pages-router.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/dist/server-root/server/routes/pages-router.js',
    '/app/dist/server-root/server/main.js',
    '/app/index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fullstack-typescript@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fullstack-typescript@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2019-05-25T14_05_16_779Z-debug.log
```

**Comment by gilamran** [comment]
Fixed with PR #20
